Repository RoBorregos/robocup-home, pull requests merged in 2021-02, with the labels that each got.

#117 SpeechToText/SeparateEngines
  catkin_home/src/action_selectors/launch/speech_to_text.launch
  catkin_home/src/action_selectors/launch/speech_to_text_launch.launch
  catkin_home/src/action_selectors/scripts/DeepSpeech.py
  catkin_home/src/action_selectors/scripts/DeepSpeech/deploy/ros_server.py
  catkin_home/src/action_selectors/scripts/hear.py
  catkin_home/src/action_selectors/src/azureSpeechText.cpp
  catkin_home/src/devices/scripts/AudioCapturer.py
Labels: Speech

#114 Readme update
  README.md
  SystemDesignv3_gray.png
  roborregos_logo.png
Labels: docs

#130 Hotfix/ArmVision
  catkin_home/src/arm_vision/CMakeLists.txt
Labels: type:bug
